syntax = "proto3";

package camera;

service CameraService {
  rpc GetConnectedDeviceSerialNumbers(EmptyRequest)
  returns(DeviceListResponse);
  rpc GetImage(GetImageRequest) returns(ImageResponse);
}

message EmptyRequest {}

message DeviceListResponse { repeated string serial_numbers = 1; }

message GetImageRequest { string serial_number = 1; }

message ImageResponse {
  bool   success       = 1;
  bytes  color_data    = 2;
  bytes  depth_data    = 3;
  uint32 width         = 4;
  uint32 height        = 5;
  string error_message = 6;
}
